version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /docker-credential/username
    DOCKER_REGISTRY_PASSWORD: /docker-credential/password
    DOCKER_REGISTRY_URL: /docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.13
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r AWS_CICD_Project/requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - cd AWS_CICD_Project/
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aws_cicd_project:latest" .
      - docker push "docker.io/Manasranjan5/aws_cicd_project:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../aws_cicd_project

